### ISSUE TITLE
Synchronize last reading position across devices

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/android#377]
This issue has a design component, an iOS component, an Android component and a server-side component.

The design component has two aspects. First is a UX question. Patrons must opt in to having their last reading position stored on a library server. When are they presented with this choice? How are the options presented? Once they have made their choice, how do they change to making the other choice?

Second, how do we represent 'last reading position'? We currently believe it is sufficient to use a Content Fragment Identifier. Once we add annotations, CFIs will stop working so well, but migration will happen automatically. Someone who opens a book in a version of SimplyE that supports annotations, adds an annotation, and closes the book, will have their last reading position synced using whatever format we come up with to replace CFIs.

The server-side component is primarily in place: we will use the existing annotation framework to keep track of last reading position. However, when a user who has opted in to having their last reading position syncs opts out, we will need a way to signal this to the server side, and the server side will need to delete the annotations.

Since the design task comes first I'm starting off by assigning this issue to Ricardo.

**Comment by aslagle** [comment]
There is one additional server-side change we need to make to deal with device timestamps.

My original plan was to allow 'idling' annotations to have a body, and the client could use that to store the device id and timestamp and other other information it needs. 

Aferdita was concerned that this means the device has to sync before every post to make sure there isn't a more recent annotation, and would like the server to be the place that checks whether there's a newer annotation.

**Comment by leonardr** [comment]
James and I decided that an explicit opt-in is not necessary for reading position, _if_ we delete the reading position annotation for a book when the book leaves the patron's shelf. We already know which loans you have out; knowing where you are in the book doesn't give us any additional information.

Although convenient, this auto-delete will negate a common usage of synced reading position. If you don't manage to finish a book before your loan expires, it's useful to be able to borrow it again and pick up at the same place. Overdrive does this and I've found it useful in the past.

I think the thing that needs to be opted in or out is not "do you want this synced across devices?" but "do you want us to keep track of this information even after your loan expires?"

**Comment by aslagle** [comment]
I think syncing should be opted in or out even if there's no privacy issue, because people who only use one device probably won't want it and could find it annoying. 

Even if our implementation is perfect and never sends anyone to the wrong position, it will be using people's data to sync.

Maybe it's not necessary to force a choice up front, but there should be a way to disable it if it's on by default.

**Comment by jce1028** [comment]
In light of Amy's point I think opt in is needed given the way that last reading position (as currently designed)  on the client,  has the application initiating the "bookmaking of the last reading position" for the user as opposed to the user initiating it by simply "taping" a bookmark location where they leave off when done reading for the moment.   This IMO it is a challenging use case because of current implementation which attempts to think and act on the users behalf vs basically affording the user to act on their own behalf.  Marking a bookmark at my last reading position in the analog world IMO is a simple action that people do as a habit (I currently use a paper bookmark in the paperback chapter book I am reading to my son to mark my last reading position) as opposed to placing a "dog ear" on the page which is sometimes associated as Bookmarking on digital too.

So for as a suggestion we may
1 - add a manual bookmark last reading position control so that synching is "opted in" by the explicit action of the user and the bookmarks disappear when the book comes off the shelf.
2. - add an opt in and keep the "auto-bookmarking" design with "turn on turn off" defaulted to Off so as not to auto annoy folks with pop-ups AND add auto removal when book expires.
3. - don't add and opt out feature, just do it and suffer the complaints from the annoying pop-ups.
4. - keep the current design where folks can turn the synching off (as designed) but don't resume they want to synch last reading position (in other words its an explicit "opt in" action by the user.

**Comment by aslagle** [comment]
Some further discussion from slack:
aslagle [11:40 AM] 
@leonardr  I want it to be opt-in because as a reader who only uses one device I find it really annoying

winnie [12:09 PM] 
@aslagle + @leonardr: Sync should generally be transparent, especially if you're not moving between two devices. Having it on by default should not result in any visible difference if you're only using a single device and it shouldn't be using much data at all. If those things are not the case, we should fix those things! Providing an opt-out makes sense, but I think too many people will fail to notice the feature if it's opt-in.

[12:11]  
We also need to make sure devices can "catch up" if you disable sync and then later reenable it. I'm not sure if that's the case right now. (edited)

aslagle [12:11 PM] 
if there shouldn't be any visible difference, what do you do when there's a server error? I think if a user was relying on the syncing they'd want to be notified of the error

winnie [12:15 PM] 
I think most apps usually silently fail for transient syncing errors. If there's a major problem (e.g. your credentials are bad) that requires user interaction it should tell you, but it should be quiet for temporary loss of connection and 500s and things of that nature. Instead, we should show a "Last Synced: <date>" string in settings, have a manual sync button to "Sync Now", and report an error only if a manual sync fails. This is how the app already handles bookshelf syncing: Only manual sync failures are reported (or at least that's how it was previously).

aslagle [12:16 PM] 
ok, that sounds reasonable

[12:17]  
personally, having an opt-out would make me a lot more comfortable releasing this feature

[12:17]  
there are so many reading apps where syncing drives me nuts and I don't even want it

winnie [12:18 PM] 
Mhm! I am not comfortable releasing it at all if it's not up to those silent standards described above, but I'd also like to see an opt-out.

**Comment by leonardr** [comment]
I think we can address these issues by getting pack on the path we were tending initially rather than trying to get fancy. The first time you leave the reader, we ask if you want us to sync your reading activity across devices. If you opt in, we save annotations and don't delete them. If you opt out, we don't save annotations. If you opt in and then opt out later, we delete your annotations.

**Comment by ricardoom** [comment]
Here is the Moqup project for reference. It isnt set up linearly. I can help walk through if need be. https://app.moqups.com/digitalrepository@nypl.org/7UMo8UAGyv/view

**Comment by winniequinn** [comment]
@ricardoom I'd love if you could walk me through this when you have a chance! I would like to get clarification around a few things before we can move on to writing copy.

**Comment by ricardoom** [comment]
No problem, we can discuss tomorrow (2/28) at your convenience.

**Comment by aferditamuriqi** [comment]
i have just a few comments:
- synchronize should be called a bit different, the terminology as it is used by google or apple is "sync" like google uses "sync highlights ad notes to google drive" and apple calls this "Sync Bookmarks and notes" we could call it "Sync bookmarks and last reading position" or something along those lines. 

- the sync settings needs to be under the account itself, for example NYPL or Brooklyn, and if a library similar to Instant classics doesn't require login, there will be no setting to sync bookmarks or last reading position.

- the second screen, we do not need two setting for enabling for this and enabling across devices. enabling means the patron decided to sync across devices. disabling at that point the patron will be asked "disable only for this device or for all devices" 

- there is one screen missing (in my opinion). once we roll out this feature, when the patron updates and opens the app for the first time after the update, we need to introduce this new feature and ask them what they would like to do "sync or no sync" and after that initial setup, they would be able to make changes in the settings 

(i'll be uploading the screenshots in a little while based on the mockups)
